# Generated by Django 4.2.7 on 2024-10-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_assign_default_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('bill_payment', 'Bill Payment')], max_length=20),
        ),
    ]
